### ISSUE TITLE
`cargo test --all-features` fails

### ISSUE THREAD

**Issue by dkg** [rust-lang/log#381]
from git master, if i run `cargo test --all-features`, i see:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running target/debug/deps/log-7d6eb7ffa43b7118

running 45 tests
test kv::key::tests::key_from_string ... ok
test kv::source::std_support::tests::btree_map ... ok
test kv::source::std_support::tests::get ... ok
test kv::source::std_support::tests::count ... ok
test kv::source::tests::count ... ok
test kv::source::std_support::tests::hash_map ... ok
test kv::source::tests::source_is_object_safe ... ok
test kv::source::tests::get ... ok
test kv::source::tests::visitor_is_object_safe ... ok
test kv::value::fill::tests::fill_cast ... ok
test kv::value::fill::tests::fill_value_borrowed ... ok
test kv::value::fill::tests::fill_value_owned ... ok
test kv::value::impls::tests::test_to_value_display ... ok
test kv::value::internal::cast::std_support::tests::primitive_cast ... ok
test kv::value::internal::fmt::tests::fmt_cast ... ok
test kv::value::internal::cast::tests::primitive_cast ... ok
test kv::value::internal::sval::tests::sval_cast ... ok
test kv::value::internal::sval::tests::test_from_sval ... ok
test kv::value::internal::sval::tests::test_sval_structured ... ok
test serde::tests::test_level_case_insensitive ... ok
test serde::tests::test_level_de_error ... ok
test kv::value::impls::tests::test_to_value_structured ... ok
test serde::tests::test_level_filter_case_insensitive ... ok
test serde::tests::test_level_filter_de_bytes ... ok
test serde::tests::test_level_de_bytes ... ok
test serde::tests::test_level_filter_de_error ... ok
test serde::tests::test_level_ser_de ... ok
test tests::test_cross_eq ... ok
test tests::test_error_trait ... ok
test tests::test_level_from_str ... ok
test tests::test_level_show ... ok
test tests::test_levelfilter_from_str ... ok
test tests::test_levelfilter_show ... ok
test tests::test_metadata_builder ... ok
test serde::tests::test_level_filter_ser_de ... ok
test tests::test_metadata_convenience_builder ... ok
test tests::test_record_builder ... ok
test tests::test_record_complete_builder ... ok
test tests::test_record_convenience_builder ... ok
test tests::test_record_key_values_builder ... ok
test tests::test_to_level ... ok
test tests::test_record_key_values_get_coerce ... ok
test tests::test_to_level_filter ... ok
test tests::test_cross_cmp ... ok
test kv::value::fill::tests::fill_multiple_times_panics ... ok

test result: ok. 45 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/filters-8e7b236d082cd8bd
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `None`,
 right: `Some(Error)`', tests/filters.rs:71:5
stack backtrace:
   0:     0x556fd8283524 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6001c6574450335d
   1:     0x556fd829461d - core::fmt::write::h1371734f6a7c7bc2
   2:     0x556fd8282845 - std::io::Write::write_fmt::h5ee928f19b08369c
   3:     0x556fd827c84e - std::panicking::default_hook::{{closure}}::h6b521085a6513c53
   4:     0x556fd827c560 - std::panicking::default_hook::h3e3fe9b536fd99f6
   5:     0x556fd827ceeb - std::panicking::rust_panic_with_hook::h3d899269d6b7f8f7
   6:     0x556fd827ca8e - std::panicking::continue_panic_fmt::h22635bd1aa2db87e
   7:     0x556fd827c9cf - std::panicking::begin_panic_fmt::h4934e76a4a1dca0f
   8:     0x556fd827797b - filters::last::h6ea39f99f73e96a2
                               at tests/filters.rs:71
   9:     0x556fd82771c8 - filters::test::h018f9be09c67b83d
                               at tests/filters.rs:50
  10:     0x556fd8276ee5 - filters::main::h5cb267d978caf4dd
                               at tests/filters.rs:40
  11:     0x556fd82742e0 - std::rt::lang_start::{{closure}}::h99add10a92b1f5d8
                               at /usr/src/rustc-1.40.0/src/libstd/rt.rs:61
  12:     0x556fd827c913 - std::panicking::try::do_call::h405fa073712ab5d5
  13:     0x556fd8283eea - __rust_maybe_catch_panic
  14:     0x556fd827fd39 - std::rt::lang_start_internal::he63ceb3eba03dd55
  15:     0x556fd82742b9 - std::rt::lang_start::h2e31d45daa3b065e
                               at /usr/src/rustc-1.40.0/src/libstd/rt.rs:61
  16:     0x556fd82779ca - main
  17:     0x7fb00fb9dbbb - __libc_start_main
  18:     0x556fd82741aa - _start
  19:                0x0 - <unknown>
error: test failed, to rerun pass '--test filters'
```
This is also a problem at tags 0.4.8 and 0.4.9.  (i confess i don't really understand what it means exactly)

It's likely to cause problems for [the debian package for this crate](https://tracker.debian.org/pkg/rust-log) as well, since we typically try to run `cargo test --all-features`.

**Comment by KodrAus** [comment]
Ah, unfortunately `log`'s features are set up in such a way that running with `--all-features` doesn't really make sense (it uses features to set minimum levels at compile-time). It's unfortunate for tests to fail though since `--all-features` should be a perfectly legitimate flag so we should do something about the filters tests so they don't run unless the feature set makes sense to them.
